AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TrainingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/training/handler.create
      Runtime: nodejs20.x
  TrainerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: services/trainer/handler.create
      Runtime: nodejs20.x
